import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import React from "react";
import Image from "next/image";
import backgroundImage from "@/public/absract_upscaled.png";
import {ConvexAuthNextjsServerProvider} from "@convex-dev/auth/nextjs/server";


const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <ConvexAuthNextjsServerProvider>
            <html lang="en">
            <body className={inter.className}>
            <Image
                src={backgroundImage}
                alt="Background"
                fill
                quality={100}
                className="z-[-1]"
            />
            {children}</body>
            </html>
        </ConvexAuthNextjsServerProvider>

    );
}
